// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_WP1ZdGOH5f7wpzmRyNxpDekJN17qtF4',
    appId: '1:85837299824:web:f80e67344a7abf8e1234b5',
    messagingSenderId: '85837299824',
    projectId: 'myteleclinic-e56d6',
    authDomain: 'myteleclinic-e56d6.firebaseapp.com',
    storageBucket: 'myteleclinic-e56d6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmbSlOOAxDIBd3BWRBw0Ml3N3jS_pY2tA',
    appId: '1:85837299824:android:1f4fa94b414cb55e1234b5',
    messagingSenderId: '85837299824',
    projectId: 'myteleclinic-e56d6',
    storageBucket: 'myteleclinic-e56d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO7E-u9wNJP-9fYtahqkdfii_-AGKnlYY',
    appId: '1:85837299824:ios:8d9644ae7ec3da641234b5',
    messagingSenderId: '85837299824',
    projectId: 'myteleclinic-e56d6',
    storageBucket: 'myteleclinic-e56d6.appspot.com',
    androidClientId: '85837299824-v85767gdc10cuuqenh9h51sd1n9k4j8b.apps.googleusercontent.com',
    iosClientId: '85837299824-aeihitrlpc79dhk75p9gj9rf0iihfsj6.apps.googleusercontent.com',
    iosBundleId: 'com.example.myTeleclinic',
  );
}
